# Ghost Configuration
# Generated by xCloud OneClick Template Engine

url=https://{{ domain }}
NODE_ENV=production
server__host=0.0.0.0
server__port=2368

# Ghost database
database__client=mysql
database__connection__host=db
database__connection__database={{ _generated.db_name }}
database__connection__user={{ _generated.db_user }}
database__connection__password={{ _generated.db_password }}

# MySQL sidecar
MYSQL_ROOT_PASSWORD={{ _generated.db_root_password }}
MYSQL_DATABASE={{ _generated.db_name }}
MYSQL_USER={{ _generated.db_user }}
MYSQL_PASSWORD={{ _generated.db_password }}
